# NumPy for Data Science

A complete hands-on guide to NumPy with examples and explanations.

**Skills Covered**
- Arrays
- Indexing
- Slicing
- Broadcasting
- Statistics
- Linear Algebra
- Random Numbers

An array is a collection of multiple values stored in a single variable.
All the elements in a NumPy array usually have the same data type, and they are stored in continuous memory,
which makes them very fast for numerical operations.

Simple Definition

 Array = a container that stores multiple values in an ordered structure.
numpy definition
NumPy (short for Numerical Python) is an open-source library for the Python programming language that 
serves as the fundamental package for scientific computing and numerical analysis.

In [3]:
import numpy as np

In [13]:
a= np.array([1,2,3,45])
a


array([ 1,  2,  3, 45])

In [9]:
n= np.array([1,3,3.4,'manoj'])
print(n)

['1' '3' '3.4' 'manoj']


In [10]:
l= [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr = np.arange(0,11,2)
arr


array([ 0,  2,  4,  6,  8, 10])

In [21]:
arr= np.ones((3,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [23]:
# linspace used to distribute uniform linspace among intervel of numbers
# in below it generates 5 numbers between 0 and 1 with same linspace among them
arr= np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
# generating an randam numbers using numpy
arr= np.random.rand(10)
arr
# the output is between 0 to 1  # it is an standardition in stats which lies b/w 0 and 1

array([0.21108465, 0.70300486, 0.3274457 , 0.72675821, 0.7706971 ,
       0.13650743, 0.45434661, 0.31652401, 0.36906555, 0.44886578])

In [31]:
# grnrtating an random number using arrays with RANDOM.RANDINT key word is used to generate number
arr = np.random.randint(6)
arr

3

In [33]:
n = np.random.randint(1,20,5)
n

array([ 3,  9, 11, 12,  4], dtype=int32)

In [34]:
# generating an random number with in range we want and giving an condition that need only 10 integers
arr = np.random.randint(1,20,10)
arr

array([16,  1,  4, 13, 10, 19, 14,  3, 15,  6], dtype=int32)

In [40]:
#ARRAY ATTRIBUTRS --> array attributes are the properties or characteristics that describe an array.
# Array attributes describe the type, size, indexing, memory location, and dimensions of an array.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
arr.size

9

In [38]:
arr.shape


(3, 3)

In [39]:
arr.dtype

dtype('int64')

In [46]:
# array methods
#Array methods are built-in functions that allow us to perform different operations on the elements of an array.
m= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
m.min()

np.int64(1)

In [48]:
m.max()

np.int64(12)

In [49]:
m.sum()

np.int64(78)

In [52]:
# column wise sum we use axis 0   
np.sum(m,axis = 0)

array([22, 26, 30])

In [56]:
#  row wise summation we ues axis 1
# we are using 0 and 1 because it is an 2 dimension array that we taken as input
np.sum(m,axis = 1)

array([ 6, 15, 24, 33])

In [57]:
m.mean()

np.float64(6.5)

In [58]:
m.std()

np.float64(3.452052529534663)

In [59]:
# it will gives an index of an maximum number
m.argmax()

np.int64(11)

In [60]:
# it will gives an index of min munber
m.argmin()

np.int64(0)

In [62]:
# Reshaping and Resizinge
n = np.arange(1,31)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [64]:
# we are reshaping the size based on the rows and columns as 6,5 respectively
n.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[1:5]

array([2, 3, 4, 5])

In [6]:
arr[1:4]

array([2, 3, 4])

In [8]:
arr[4:6]

array([5, 6])

In [ ]:
arr[:,2]

In [1]:
import numpy as np

In [10]:
array = np.arange(1,21)
m = array.reshape(4,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
m[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [15]:
m[2:,3:]

array([[14, 15],
       [19, 20]])

In [16]:
#extracting an one  column
m[:,2]

array([ 3,  8, 13, 18])

In [23]:
m[1,:]

array([ 6,  7,  8,  9, 10])

In [36]:
#Boolean indexing in NumPy is a way to filter elements of an array using True/False conditions.

m= np.arange(10,21)
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
boolean_index = m%2==0
boolean_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [39]:
m = m[boolean_index]
m

array([10, 12, 14, 16, 18, 20])

In [42]:
#Array operations
# to perform array operations two arrays should be in an same size (5*5,6*6)
a1 = np.arange(1,6)
a2 = np.arange(6,11)
a1

array([1, 2, 3, 4, 5])

In [41]:
a2

array([ 6,  7,  8,  9, 10])

In [43]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [44]:
a1-a2

array([-5, -5, -5, -5, -5])

In [45]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [46]:
a1//a2

array([0, 0, 0, 0, 0])

In [47]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [48]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [50]:
a1.min()

np.int64(1)

In [51]:
a2.max()

np.int64(10)

In [52]:
# Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the larger one.
#it avoids writing loops and makes operations fast and memory efficient.
a1+1

array([2, 3, 4, 5, 6])

In [53]:
a1+10

array([11, 12, 13, 14, 15])

In [55]:
array3 = np.arange(1,26).reshape(5,5)
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
array3=array3+5
array3

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [60]:
array3

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

deep and shallow copy
deep copy and shallow copy describe how data is duplicated when creating a new variable from an existing object.

In [ ]:
Shallow Copy
#A shallow copy creates a new variable, but the data is still shared with the original object.
#If you modify the copied object, the original may also change.

In [63]:
a = np.array([1,2,3,4])
b= a.view()  #shallow copy
b[0] = 99
print(a)
print(b)  #Here both arrays changed because they share the same memory.

[99  2  3  4]
[99  2  3  4]


In [64]:
a = np.array([1,2,3,4])
b= a  #shallow copy
b[0] = 99
print(a)
print(b)

[99  2  3  4]
[99  2  3  4]


In [66]:
a = ([1,2,3,4,5])
b = a.copy()
b[0]= 300
print(a)
print(b) #Now the original array remains unchanged

[1, 2, 3, 4, 5]
[300, 2, 3, 4, 5]


In [ ]:
#Shallow copy → shares memory with original
#Deep copy → creates independent memory


In [76]:
mat1 =np.array ([[1,2,3],[4,5,6],[5,2,7]])
mat2 =np.array([[6,7,8],[8,9,7],[7,7,5]])
print(mat1)
print(mat2)

[[1 2 3]
 [4 5 6]
 [5 2 7]]
[[6 7 8]
 [8 9 7]
 [7 7 5]]


In [77]:
q= np.array(mat1-mat2)
q

array([[-5, -5, -5],
       [-4, -4, -1],
       [-2, -5,  2]])

In [78]:
q= np.array(mat1+mat2)
q

array([[ 7,  9, 11],
       [12, 14, 13],
       [12,  9, 12]])

In [80]:
np.dot(mat1,mat2)

array([[ 43,  46,  37],
       [106, 115,  97],
       [ 95, 102,  89]])

In [82]:
mat2.T

array([[6, 8, 7],
       [7, 9, 7],
       [8, 7, 5]])

In [83]:
mat1.T

array([[1, 4, 5],
       [2, 5, 2],
       [3, 6, 7]])

In [84]:
a = np.array([1,2,3,4,5]) # stack array
b = np.array([6,7,8,9,0])
c=np.vstack((a,b))
c

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [85]:
m = np.hstack((a,b))
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [87]:
n = np.column_stack((a,b))
n

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 0]])

In [88]:
c = np.arange(16).reshape(4,4) # splitting
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
m = np.hsplit(c,4)
m

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [92]:
m = np.vsplit(c,2)
m

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [96]:
o =np.array([[0, 1, 2, 3],
        [4, 5, 6, 7]])
o.sum()

np.int64(28)

In [3]:
import numpy as np

In [4]:
# columns: [age,mathmarks,sciencemarks]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])
data               

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [5]:
#1 get shape of matrix
data.shape

(5, 3)

In [6]:
#2 find average age of students
np.mean(data[:,0])

np.float64(18.4)

In [7]:
#3 extract maths marks
data[:,1]

array([85, 92, 76, 65, 90])

In [8]:
# find highest marks in science
np.max(data[:,2])

np.int64(95)

In [9]:
# get student of student who get more than 90 marks in maths
data[data[:,1]>90]

    

array([[19, 92, 88]])

In [10]:
# increase maths by +5 to all
data[:,1]+5

array([90, 97, 81, 70, 95])

In [12]:
# find the studens whose age is lessthan than 19
data[data[:,0]<19] 

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [17]:
# calculate average marks in each subject 
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [22]:
#get student marks at least more than 80
data[(data[:,1]>=80)& (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [23]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [31]:
# replace less than 75 with zero(0) some wrong haaa
data[data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])

In [32]:
import numpy as np

np.linspace(3.5, 10, 3, 
            dtype = np.int32)

array([ 3,  6, 10], dtype=int32)

In [34]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a, b),axis =0)
print(res)

[[1 2 3]
 [4 5 6]]


In [38]:
a = np.array([1,2,3])
print(a+11)

[12 13 14]


In [45]:
a = np.array([1,2,3])
b = np.array([4,5,6])

vstk = np.vstack((a,b))
vstk

concet = np.concatenate((a,b))
concet

stk = np.stack((a,b))
stk

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
import numpy as np

In [2]:
creating_array = np.array([12,3,4,5,6,7,89])
creating_array

array([12,  3,  4,  5,  6,  7, 89])

In [8]:
ones_array = np.ones([2,2])
ones_array

array([[1., 1.],
       [1., 1.]])

In [12]:
twoes_array = np.zeros([2,2])
twoes_array

array([[0., 0.],
       [0., 0.]])

In [26]:
import numpy as np
data = np.arange(20)
shape = np.reshape(data, (4,5))
print(data)
print(shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
import numpy as np

data = np.arange(20)
shape = np.reshape(data, (4,5))

print(data)
print(shape)
print(data.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
20


In [32]:
arr = np.arange(12)
new_arr = arr.reshape(3,4)
print(arr)
print(new_arr)
print(arr.size)
print(arr.ndim)
print(new_arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
12
1
2


In [35]:
arr = np.arange(9)
arr1 = np.reshape(arr,(3,3))
print(arr)
print(arr1)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
print(arr[-4])

5


In [45]:
print(arr1[2:,1])

[7]


In [46]:
print(arr1[2:,0])

[6]


In [47]:
print(arr[0:4])

[0 1 2 3]


In [48]:
print(arr[:3])

[0 1 2]


In [49]:
print(arr[3:])

[3 4 5 6 7 8]


In [53]:
arr1[0,:]

array([0, 1, 2])

In [56]:
arr1[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [58]:
arr = np.arange(9)
arr1 = np.resize(arr,(3,5))
print(arr)
print(arr1)

[0 1 2 3 4 5 6 7 8]
[[0 1 2 3 4]
 [5 6 7 8 0]
 [1 2 3 4 5]]


In [62]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)
print(np.sqrt(a))
print(np.power(b,4))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[    1    64  2187 65536]
[1.         1.41421356 1.73205081 2.        ]
[ 625 1296 2401 4096]


In [63]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436]


array([1. , 2. , 0.6, 0.8, 0.7])

In [70]:
a = np.array([1,2,3,4,5,6])
print(a+4)
print(a-6)

[ 5  6  7  8  9 10]
[-5 -4 -3 -2 -1  0]


In [76]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([10,20,30])
print(b+a)

[[11 22 33]
 [14 25 36]]


In [82]:
a = np.array([1,2,3,8,9])
np.flip(a)

array([9, 8, 3, 2, 1])

In [83]:
a = np.array([[1,2,3],
             [4,5,6]])
a[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [84]:
a = np.array([[1,2,3],
             [4,5,6]])
np.flip(a)

array([[6, 5, 4],
       [3, 2, 1]])

In [86]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

#concat = np.concatenate(a,b)

concat = np.concatenate((a, [b]))

print(concat)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


In [94]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
np.reshape(x,[3,4])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
new = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
new.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
new.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
import numpy as np
arr =  np.array([1,2,3,4])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.cumsum(arr))
print(np.percentile(arr,3))
print(np.cumprod(arr))

10
2.5
2.5
1.118033988749895
1.25
4
1
0
3
[ 1  3  6 10]
1.09
[ 1  2  6 24]


In [1]:
import numpy as np
arr= np.array([1,2,3])
print(arr.shape)

(3,)


In [3]:
m = np.array([[1,2,3],[4,5,6]])
m.shape

(2, 3)

In [7]:
a = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
a.shape

(3, 1, 3)

In [10]:
arr = np.arange(9)
arr1 = np.reshape(arr,(3,3))
print(arr)
print(arr1)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
a= np.arange(1,16)
a.reshape(5,1,3)


array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]]])

In [13]:
a= np.arange(1,16)
a.reshape(1,3,5)


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [14]:
a= np.arange(1,16)
a.reshape(3,1,5)


array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]]])

In [30]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m[1])
print(m[1,1])
print(m[0,1:3])
print(m[0:2])
print(m[2,0::2])
print(m[0:3,0])

[4 5 6]
5
[2 3]
[[1 2 3]
 [4 5 6]]
[7 9]
[1 4 7]


In [10]:
import numpy as np
m = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(m)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
print(m[0,0::2])

[[1 2 3]]


In [12]:
print(m[0,1::2])

[[4 5 6]]


In [ ]:
print(m[

In [24]:
import numpy as np
arr = np.arange(1,19)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [31]:
 arr1 = arr.reshape(3,2,3)

In [32]:
arr1.ndim

3

In [36]:
print(arr1[0::2,:,1:])

[[[ 2  3]
  [ 5  6]]

 [[14 15]
  [17 18]]]


In [38]:
print(arr1[0::2,:,1::2])

[[[ 2]
  [ 5]]

 [[14]
  [17]]]


In [40]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [45]:
w = np.linspace(0,1,3)
w

array([0. , 0.5, 1. ])

In [48]:
e = np.linspace(0,10,6)
e

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [49]:
p = np.linspace(0,1,10)
p

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [50]:
e = np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
m = np.ones((3,4))
m

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
d = np.full(5,'apple')
d

array(['apple', 'apple', 'apple', 'apple', 'apple'], dtype='<U5')

In [53]:
f = np.full((4,5),7)
f

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [60]:
print(f.dtype)


int64


In [61]:
i = np.identity(7)
i

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [63]:
# np.eye()
# create an rectanglar matrix
v = np.eye(5)
v

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
v = np.eye(3,5)
v

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [68]:
w = np.random.rand(10)
w

array([0.84272236, 0.36198755, 0.60304291, 0.42883206, 0.93866544,
       0.9544612 , 0.21295891, 0.00620593, 0.74373483, 0.65891166])

In [69]:
e = np.random.randint(1,101,50)
e

array([ 26,  33,  96,  52,  22, 100,  56,  38,   5,  55,  21,  89,  84,
        21,  10,  35,  81,  26,  60,  34,   2,  44,  85,  69,  71,  58,
        54,  37,  77,  74,  59,  10,  29,  58,   8,  39,  75,  84,  66,
        66,   2,  31,  33,  69,  92,  11,  74,  62,  67,  49], dtype=int32)

In [70]:
e = np.random.randint(1,101,size=(4,5))
e

array([[56, 29, 78, 77, 89],
       [52, 64, 34,  1, 82],
       [49, 96, 55, 95, 12],
       [39, 46, 86,  2, 40]], dtype=int32)

In [1]:
import numpy as np
arr = np.random.randint(100,200,10)
print(arr)

[151 117 108 123 105 106 163 189 164 109]


In [2]:
print(arr%2==0)
print(arr+5)

[False False  True False False  True False False  True False]
[156 122 113 128 110 111 168 194 169 114]


In [4]:
w = arr<150
print(w)

[False  True  True  True  True  True False False False  True]


In [5]:
print(arr[arr<150])

[117 108 123 105 106 109]


In [8]:
filter = arr%2!=0
print(arr[filter])

[151 117 123 105 163 189 109]


In [9]:
filter = np.random.randint(0,2,10)
filter

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1], dtype=int32)

In [13]:
w =np.array( [[1,2,3],[4,5,6],[5,2,7]])
arr= w+5
arr

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [10,  7, 12]])

In [19]:
l=[[1,2,3],[4,5,6],[7,8,9]]
len(l)

3

In [32]:
dice = np.random.randint(1,7,10)
amount= 200
for i in dice:
    if (i == 6):
        amount+=50
    else:
        amount-=20
print(amount)    

280


In [9]:
import numpy as np
arr = np.arange(0,28)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [10]:
arr1 = arr.reshape(7,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [11]:
arr2 = arr.reshape(2,2,7)
arr2

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27]]])

In [12]:
 arr1[0]

array([0, 1, 2, 3])

In [15]:
print(arr1[:,3])

[ 3  7 11 15 19 23 27]


In [16]:
print(arr1[:,0])

[ 0  4  8 12 16 20 24]


In [18]:
arr1[1:4,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [21]:
num = np.random.randint(1,100,10)
num

array([94, 56, 18, 18, 12, 74, 27, 86, 36, 83], dtype=int32)

In [28]:
#even = num%2==0
print(num[num%2==0])


[94 56 18 18 12 74 86 36]


In [35]:
a = (num[num%2==0])
a

array([94, 56, 18, 18, 12, 74, 86, 36], dtype=int32)

In [38]:
print(a[a>50])

[94 56 74 86]


In [42]:
a.mean()

np.float64(49.25)

In [44]:
b= (num[num%2!=0])
print(b)

[27 83]


In [45]:
b.mean()

np.float64(55.0)

In [48]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[-2,-4,3],[2,7,4]])
print(np.concatenate((a,b)))
    

[[ 1  2  3]
 [ 4  5  6]
 [-2 -4  3]
 [ 2  7  4]]


In [49]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[-2,-4,3],[2,7,4]])
print(np.concatenate((a,b),axis=1))
    

[[ 1  2  3 -2 -4  3]
 [ 4  5  6  2  7  4]]


In [50]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[-2,-4,3],[2,7,4]])
print(np.concatenate((a,b),axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [-2 -4  3]
 [ 2  7  4]]
